### ISSUE TITLE
Missing Subject Key Identifier

### ISSUE THREAD

**Issue by PetraBarzin** [cabforum/smime#104]
In the Certificate Profile (Section 7.1) the Subject Key Identifier extension is missing.
According to RFC 5280, "To facilitate certification path construction, this extension MUST appear in all conforming CA certificates" and "this extension SHOULD be included in all end entity certificates"

**Comment by CBonnell** [comment]
Thanks for filing, @PetraBarzin. This is an oversight that is also present in the TLS BRs. I have submitted a PR to fix for the SMBRs.

**Comment by srdavidson** [comment]
Thank you @PetraBarzin and @CBonnell - this has been merged into the draft.
