### ISSUE TITLE
Key length of 2048 Bit beyond 2023

### ISSUE THREAD

**Issue by PetraBarzin** [cabforum/smime#105]
Section 6.1.5: "Ensure that the modulus size, when encoded, is at least 2048 bits"
The German Federal Office for Information Security (BSI) provides an assessment of the security and long-term orientation for selected cryptographic mechanisms. The use of RSA based signature and confidentiality mechanisms with a key size of 2048 Bits is compliant until end of 2023. From 2024 onwards, an RSA key length of ≥ 3000 bits will be mandatory.
With a certificate validity of 825 days you may want to require at least 3072 bits.

BSI TR-02102-1: "Cryptographic Mechanisms: Recommendations and Key Lengths" Version: 2022-1:
https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-1.pdf

**Comment by CBonnell** [comment]
One challenge of implementing larger key sizes is that there is a lack of consistency between various standards bodies for the deprecation of RSA-2048. While BSI recommends moving to at least 3000 bits from 2024, [NIST](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57pt1r5.pdf) recommends a 2030 timeline for the deprecation of RSA-2048.

The current language in the SMBRs allows CAs that are audited to conformance with BSI guidance to migrate to larger key sizes on an accelerated time frame. Given this, I think it would be best in the short term to retain the RSA-2048 requirement and we can refine in a future ballot.

**Comment by PetraBarzin** [comment]
Yes, NIST allows RSA-2048 until 2030 but this key length only provides a security strength of 112 like 3TDEA does - compared to a security strength of 128 for RSA-3072 and AES-128. According to NIST SP 800-152, a security strength of 112 bits is sufficient **for protection of Low impact-level information**. For Moderate impact-level information, a security strength of 128 is required. High-impact information requires at least a security strength of 192.

**Comment by PetraBarzin** [comment]
NSA's Commercial National Security Algorithm Suite (CNSA) requires RSA-3072 for digital signatures and key exchange, too. Look at the RFC 8603 "CNSA Suite Certificate and Certificate Revocation List (CRL) Profile" which requires at least RSA-3072 or RFC 9212 "CNSA Suite Cryptography for Secure Shell (SSH)" with the same requirement for user/client and server keys.
