### ISSUE TITLE
Identity validation: Individual identity information from incorporating sources

### ISSUE THREAD

**Issue by chrisbn** [cabforum/smime#110]
Should we also consider incorporating agency sources as a source for listed director individual identity information (akin to the Enterprise RA records, but publicly available and where the identity validation is regulated in the relevant jurisdiction of incorporation)?

**Comment by srdavidson** [comment]
Is this to determine an appropriate person to act as a corporate contact  I believe this is already allowed in 3.26 and 3.2.8.

On a related subject, 3.2.4.1 (8) allows the use of "authorized reference sources as supplementary evidence".  It currently specifies the use of such to verify the professional Title of a regulated profession in the context of the subject:title attribute.  That could be expanded to include corporate role.

**Comment by srdavidson** [comment]
Edit made for clarity 

* If a professional Title of a regulated profession in the`subject:country`, or a corporate role/Title linked to a `subject:organization`, is to be used it SHALL be verified against supporting documentation, a Reliable Data Source, or Attestation.
