### ISSUE TITLE
Identity validation: Digital signatures

### ISSUE THREAD

**Issue by chrisbn** [cabforum/smime#111]
For digital signatures (section 3.2.4.1 option 3), could we allow additional adopted standards to be used under certain conditions, for example:

- CA has a documented procedure to review adopted standards against the SMIME BRs to ensure they meet the required assurance level;
- the CA lists additional accepted standards in their CPS; and
- CA notifies these additional standards for inclusion within the SMIME BRs, but pending acceptance/rejection these standards may be used.

**Comment by timfromdigicert** [comment]
I'm curious how people interpret "If a digital signature is to be used as evidence, ..."  That seems rather vague and unverifiable/unauditable.

**Comment by srdavidson** [comment]
Proposed text at https://github.com/cabforum/smime/blob/preSBR/SBR.md#3241-attribute-collection-of-individual-identity item 4
