### ISSUE TITLE
Organizational Units: departments

### ISSUE THREAD

**Issue by chrisbn** [cabforum/smime#112]
Would departments as organizational units fit within the profile? And if yes, could they be included in organization-validated or sponsor-validated? The current definition of organizationalUnitName (section 7.1.4.2.2 item c) seems to be limited to affiliate entities, but not departments?

**Comment by srdavidson** [comment]
Our discussion was that OU may be used if verified in accordance with the requirements of Section 3.2.  Our original discussion centred on this being via a reliable data source (which in most cases would mean affiliate).
