### ISSUE TITLE
eIDAS eIDs: attribute collection and validation of individual identity

### ISSUE THREAD

**Issue by chrisbn** [cabforum/smime#119]
3.2.4.2 Validation of individual identity item 3: Validation of eID states "If authentication using an eID is used as evidence, the CA or RA SHALL confirm that the eID scheme **is suitable (for example that the eID is accessible via a notified eIDAS-Node)**, and that the individual eID is valid (i.e., not expired, suspended, or revoked).

3.2.4.1 Attribute collection of individual identity item 3: Using electronic identification schemes (eID)
"If an eID is used as evidence, the CA or RA SHALL only accept “notified” eID schemes according to Article 9 of the [eIDAS Regulation](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2014.257.01.0073.01.ENG) and the eID shall conform to eIDAS LoA “Substantial” or “High”. The CA SHALL document and publish information describing the eID and associated eID attributes it accepts."

As the condition is that the eID is notified, mentioned in 3.2.4.1, can the term "suitable" be omitted or replaced with a notification requirement in 3.2.4.2?

Since 3.2.4 Authentication of individual identity defines which attributes need to be collected, I'm not convinced about the added value of disclosing the associated eID attributes.

**Comment by srdavidson** [comment]
"associated eID attributes it accepts"

With that text I was referring to the possibilities of QEAA and EAA in the future beyond the core identity aspects of eID.
