### ISSUE TITLE
Enterprise registration authorities

### ISSUE THREAD

**Issue by russhousley** [cabforum/smime#120]
This section says:

~~~
If the Certificate Request is for a Mailbox-validated profile, the CA SHALL confirm that the mailbox holder has control of the requested email domains in accordance with [Section 3.2.2.2](https://github.com/cabforum/smime/blob/preSBR/SBR.md#3222-validating-control-over-mailbox-via-email).
~~~

Even though this is in a section about Enterprise registration authorities, if the certificate will be issued under the Mailbox-validated profile, I think it should be requiring control over the requested mailbox, not control over the whole email domain.

**Comment by srdavidson** [comment]
Thank you.  This will be updated to:

> 2. If the Certificate Request is for a `Mailbox-validated` profile, the CA SHALL confirm that the mailbox holder has control of the requested Mailbox Addresses in accordance with [Section 3.2.2.2](#3222-validating-control-over-mailbox-via-email).
