### ISSUE TITLE
Time within which CA must process the revocation request

### ISSUE THREAD

**Issue by zurinazolkaffly** [cabforum/smime#130]
In the case of an online revocation request that is capable to authenticate the user, the certificate shall revoke immediately. Is section 4.9.5 shall apply to this case? or shall exclude it?

**Comment by srdavidson** [comment]
For an authenticated request from the Subscriber 4.9.1.1 applies. The text in 4.9.5 (as is done in the TLS BR) deals more with third-party problem reports about certs.
