### ISSUE TITLE
3.2.2.2 Validating control over mailbox via email : Random Value

### ISSUE THREAD

**Issue by AshishGlobalSign** [cabforum/smime#133]
Current Text : The Random Value SHALL be reset upon each instance of the email sent by the CA and, if intended for additional use as an authentication factor, upon first use.

Question : Not sure what its trying to say, is it that if you request a random value then another before using the first that the first is no longer usable, and using it for auth also kills it for future use or its resetting the random value altogether and cant be used; I am confused here with the word each instance of the email sent and upon first use word. The request would be to explain / elaborate it a bit for everyone's understanding?

**Comment by srdavidson** [comment]
The current specification requires the RV to be changed each time the CA sends the email (this is more vigorous than the TLS BR which allows RV reuse when the same email is resent by the CA to the same address).
If the service allows a user to login to manage their cert, the same RV cannot be used as an ongoing auth code; the user should be prompted to choose their own login for ongoing use.
