### ISSUE TITLE
Do Japanese / Chinese / Cyrillic are allowed in Subject DN or Not ? 

### ISSUE THREAD

**Issue by AshishGlobalSign** [cabforum/smime#134]
Referred at 3.1.4.2 & 3.1.4.3 

Please add description whether non-latin characters such like Chinese, Japanese or Cyrillic is available in the subject DN or subjectAltName in this profile or not ?

**Comment by RufusJWB** [comment]
Please compare https://github.com/cabforum/smime/issues/80 and feel free to adapt https://github.com/cabforum/smime/pull/128 . I'm sharing your opinion that the current language of 3.1.4 can be improved in regards to non-ASCII characters

**Comment by srdavidson** [comment]
It was agreed at the F2F that such inclusions in the subjectDN are determined by the relevant RFC, so it is not needed to repeat the rules here.
