### ISSUE TITLE
Clarify the use of LDAP (and FTP) for AIA / CRL access

### ISSUE THREAD

**Issue by RufusJWB** [cabforum/smime#143]
For TLS certificates the use of any other methods than HTTP for AIA / CRL access will be prohibited.
[2022 Summer Validation SC.pdf](https://github.com/cabforum/smime/files/8883594/2022.Summer.Validation.SC.pdf)

We should clarify, how we will handle this for S/MIME certificates

**Comment by XolphinMartijn** [comment]
The current language of the preSBR allows the use of LDAP and FTP only for Legacy Profiles. The intent is for Legacy profiles to be removed over time, which would disallow it.

**Comment by XolphinMartijn** [comment]
Although I will add that when Legacy Profiles are removed, we should probably specifically disallow the use in S/MIME, to prevent any  default deny yes or no discussion

**Comment by RufusJWB** [comment]
> Although I will add that when Legacy Profiles are removed, we should probably specifically disallow the use in S/MIME, to prevent any default deny yes or no discussion

If this is the intent, we need a sentence that forbids them. Because the current language would allow them, if at least one HTTP endpoint is available.

**Comment by russhousley** [comment]
If only a CAB Forum policy OID is present, then the AIA and the CRL Distribution point MUST only use HTTP.
