### ISSUE TITLE
7.1.4.2.2 Subject CN shall allow use of Email / Mail box address ? or Shall be keep it for future version

### ISSUE THREAD

**Issue by AshishGlobalSign** [cabforum/smime#146]
Currently, in most of the implementation, the use of CN for an email address is there; do we as a group feel that we should restrict this usage or we can keep it for a future version, just wanted to initiate this thread to collect views of all parties involved.

**Comment by lahtipe5** [comment]
In Telia we would like to keep CN as email address also in the future. For us CN is the "identity" of the SMIME certificate and there is no other value than email address that would be appropriate in many use cases. I don't like the idea to create SMIME certificate without any CN value even if it is technically feasible.

**Comment by srdavidson** [comment]
As this is existing common practice, in earlier discussion we agreed to allow the use in CN and Subject email for now, and to amend in future versions if desired.
