### ISSUE TITLE
Update Build Guidelines Actions

### ISSUE THREAD

**Issue by XolphinMartijn** [cabforum/smime#192]
https://github.com/cabforum/build-guidelines-action/pull/43 was merged. We should update to the latest version. The question at stake is if we need an official ballot for this or not.

**Comment by XolphinMartijn** [comment]
This apparantly was already done!

**Comment by CBonnell** [comment]
Apologies for not seeing this sooner; I was out of pocket last week and missed this.

But yes, the latest tooling was integrated into the preSBR branch prior to the SMBRs going to ballot, as the improved tooling was required to get some tables to render correctly.
