### ISSUE TITLE
Deprecation date for Legacy Generation profiles

### ISSUE THREAD

**Issue by XolphinMartijn** [cabforum/smime#193]

**Comment by srdavidson** [comment]
Here is a summary of the differences between the Legacy and the Multi/Strict generation profiles as discussed in the SMCWG on April 10:

https://cabforum.org/posts/2024/2024-04-10-legacy-deprecation/SMCWG_20240410_Final.pdf

**Comment by srdavidson** [comment]
Draft ballot sits here https://github.com/srdavidson/smime/blob/Ballot-SMC08/SBR.md
