### ISSUE TITLE
No requirement to include countryName if stateOrProvinceName or localityName are present

### ISSUE THREAD

**Issue by CBonnell** [cabforum/smime#211]
I believe this is an oversight, but there is currently no requirement for any of the identity certificate types (IV, OV, SV) to include a countryName if stateOrProvinceName and/or localityName subject attributes are present.

Requiring this attribute would align the SMBR profile with other CABF standards. But more importantly, the absence of the countryName field can lead to ambiguity (Paris, France or Paris, Texas)?

**Comment by srdavidson** [comment]
In general, our discussions indicated a wish to keep the use of Subject "geographic" attributes flexible, particularly in the Legacy profile ... with the possibility of refining the Strict profile later.
Would the following text additions resolve the concern of having lower level address fields that are not "qualified" by the corresponding larger geographic unit?

7.1.4.2.2 (j)
The subject:streetAddress field SHALL only be used if the subject:localityName or subject:stateOrProvinceName field is present.

7.1.4.2.2 (k)
The subject:localityName field SHALL only be used if the subject:countryName field is present.

7.1.4.2.2 (l)
The subject:stateOrProvinceName field SHALL only be used if the subject:countryName field is present.

7.1.4.2.2 (m)
The subject:postalCode field SHALL only be used if the subject:localityName or subject:stateOrProvinceName field is present.

**Comment by srdavidson** [comment]
See proposed text at https://github.com/srdavidson/smime/commit/9fa93572bb00daa83444ac9226789d4069d88df6
