### ISSUE TITLE
Pseudonym with Subject name fields

### ISSUE THREAD

**Issue by srdavidson** [cabforum/smime#213]
In the Legacy generation profiles for Sponsor-validated and Individual-validated, changes were made that separated the use of a Pseudonym in the commonName from the (optional) subject:Pseudonym field.

While the standard (7.1.4.2.2 f) forbids using the subject:Pseudonym if the subject:givenName and subject:surname fields are used, it is silent on the use of Pseudonym in the commonName in combination with the subject:givenName and subject:surname fields.

That should presumably be clarified.

**Comment by robplee** [comment]
Duplicate of #203 ?

**Comment by srdavidson** [comment]
Rolling into Rob's earlier #203
