### ISSUE TITLE
subject:organizationIdentifier requires subject:countryName to be present

### ISSUE THREAD

**Issue by robplee** [cabforum/smime#222]
I think there's an inconsistency between how subject:countryName is inclusions are described in 7.1.4.2.4 and 7.1.4.2.5, and the text around subject:organizationIdentifiers in Appendix A.1.

7.1.4.2.4 and 7.1.4.2.5 say that for organization-validated and sponsor-validated profiles, countryName MAY be present, but A.1 says that in the organizationIdentifier field (which SHALL be included for these profiles) then "the country code used in the Registration Scheme SHALL match that of the subject:countryName in the Certificate".  The profiles say it's an optional field, but one of the mandatory fields says that it must be present.

If the goal is to allow countryName to be optional in the organization/sponsor validated profiles, then should the A.1 paragraph instead read something like this:

If a subject:countryName is present in the Certificate, as specified in Section 7.1.4.2.2, the country code used in the Registration Scheme identifier SHALL match that of the subject:countryName.

**Comment by srdavidson** [comment]
See https://github.com/srdavidson/smime/commit/314a31b59f8945266bb66451f51b810dad9924c3
