### ISSUE TITLE
Ensure all Mailbox Addresses in cert are included in the SAN

### ISSUE THREAD

**Issue by clintwilson** [cabforum/smime#224]
If a Mailbox Address appears in an S/MIME certificate, it must also appear in the SAN extension of that certificate.

**Comment by clintwilson** [comment]
@CBonnell Is this a lint included in pkilint? `VALIDATION_EMAIL_ADDRESS_IN_ATTRIBUTE_MISSING_FROM_SAN` looks like this is what it's checking, but I wasn't positive if that's the case.

**Comment by CBonnell** [comment]
@clintwilson Yes, `VALIDATION_EMAIL_ADDRESS_IN_ATTRIBUTE_MISSING_FROM_SAN` is the finding that is reported when the requirement that @bcmorton quoted is violated.

**Comment by srdavidson** [comment]
It seems we have coverage on this.
