### ISSUE TITLE
Incorrect Certificate profiles definition in Section 1.2

### ISSUE THREAD

**Issue by XolphinMartijn** [cabforum/smime#227]
Section 1.2 reads:

| Certificate Type | Description |
|------|-------------|
| Mailbox-validated | Subject is limited to (optional) `subject:emailAddress` and/or `subject:serialNumber` attributes. |

However, further down in section 7.1.4.2.3, we also allow subject:commonName:

| Attribute | Legacy | Multipurpose | Strict |
|-----------|--------|--------------|--------|
| `commonName` | MAY  | MAY | MAY |

Suggest we resolve this in a cleanup ballot

**Comment by srdavidson** [comment]
Enjoy the cross referencing!

But when read in conjunction with 7.1.4.2.2 (a), the CN may only include a repeat of the email.

**Comment by XolphinMartijn** [comment]
Not so fast ;)

>But when read in conjunction with 7.1.4.2.2 (a), the CN may only include a repeat of the email.

Agreed, but the text in section 1.2 says that the subject is limited to the two attributes. subject:commonName is a different attribute, even if the value of the attribute is the same as the value of the subject:emailAddress attribute.

**Comment by CBonnell** [comment]
I agree with @XolphinMartijn that 1.2 should be aligned with 7.1.4.2.2 (a). As a concrete proposal I suggest modifying the text in section 1.2 to:

> Subject is limited to (optional) `subject:emailAddress`, `subject:commonName`, and/or `subject:serialNumber` attributes.

**Comment by srdavidson** [comment]
I understand now.  https://github.com/srdavidson/smime/commit/ab1c54a94c9ae194854add42569234c4e3d26680 should address this.
