### ISSUE TITLE
Use of EL country code in VAT Registration Scheme for OrgID

### ISSUE THREAD

**Issue by srdavidson** [cabforum/smime#229]
For the subject:organizationIdentifier, 7.1.4.2.2 (d) specifies that the Registration Scheme must use an 2 character ISO 3166 country code for the nation in which the Registration Scheme is operated.

There is an exception for Registration Scheme that is documented in Article 215 of https://eur-lex.europa.eu/eli/dir/2006/112/oj

This allows Greece to use the prefix EL in its VAT reference numbers,

**Comment by srdavidson** [comment]
See draft at https://github.com/srdavidson/smime/commit/6893163d8db45cf31d1696976c97d94c8c62ad5c

Appendix A includes this stipulation: 

> With the exception of the LEI and INT Registration Schemes, the country code used in the Registration Scheme identifier SHALL match that of the `subject:countryName` in the Certificate as specified in [Section 7.1.4.2.2](#71422-subject-distinguished-name-fields). 

I don't think this needs updating ... however if you think we need more clarity we could add:

> For the VAT Registration Scheme, Greece may use EL as a prefix in the Registration Scheme in conjunction with GR in the `subject:countryName`.

**Comment by CBonnell** [comment]
I think the extra sentence describing that "GR" must continue to be used for `countryName` is valuable to include.

**Comment by srdavidson** [comment]
Thanks Corey - see https://github.com/srdavidson/smime/commit/efe84ea6e2ce93b90c37727a4a007d3e3ea8dd92

**Comment by srdavidson** [comment]
Updating to match the EV ballot treatment 

https://github.com/srdavidson/smime/compare/6fba8acc6f0fe840b3908d8d54ab23a816946d85...e7e01c079f69fab04404f95368c976e7893a48cf
