### ISSUE TITLE
Add definition of Sponsor(ed)

### ISSUE THREAD

**Issue by defacto64** [cabforum/smime#23]
I'd suggest to add the definition of "Sponsored" and/or "Sponsor-validated" to the Definitions, as it may not be obvious what do they mean.

**Comment by defacto64** [comment]
It works for me, but I have two doubts:
1) I suppose it's obvious that that the Legal Person mentioned in the definition MUST be the Enterprise RA itself. For instance, an Enterprise RA portal (or centralized cert mgtm portal) configured for "Some Bank Ltd" can only perform Registration for S/MIME certificates containing O="Some Bank Ltd" (or an affiliated thereof). My doubt is that, if do not specify this, the definition may lend itself to misinterpretation.
2) What types of relationship between the Natural Person and the Legal Person does the Sponsor-validated policy implies? Just any type, whatever, or one of a number of allowed types? For instance, the employee-employer case seems okay to me, but what about the company-supplier case? or the company-customer case? Are all these cases acceptable, or do we prefer to clarify which are and which are not?

**Comment by srdavidson** [comment]
HI Adriano - thanks for the feedback.

There is [additional language in 1.3.2](https://github.com/cabforum/smime/blob/preSBR/SBR.md#1321-enterprise-registration-authorities) dealing with ERA scope.

**Sponsor-validated**: Refers to a Certificate Profile Subject which combines Individual (Natural Person) attributes in conjunction with an `subject:organizationName` (an associated Legal Person) attribute. Registration for Sponsor-validated Certificates MAY be performed by an Enterprise RA where the `subject:organizationName` is either that of the delegated enterprise, or an Affiliate of the delegated enterprise, or that the delegated enterprise is an agent of the named Subject Organization.

**Comment by defacto64** [comment]
You are right, my slop of attention, as regards my point #1. 
So it's already clear enough that the organizatioName must be the ERA itself (or an affiliated thereof).

But it does not (seem to me) to answer my doubts #2.
Would you help me see where the current language addresses my concern #2 ?

**Comment by srdavidson** [comment]
The Sponsor-validated type doesn't describe the nature of the relationship between the Natural Person and the Legal Person; it just says that the org has approved that person to be associate with their O attribute and email domain.
