### ISSUE TITLE
Use of Third Party OIDs

### ISSUE THREAD

**Issue by srdavidson** [cabforum/smime#235]
It's been discussed on WG teleconferences that use of third-party OIDs and EKU s allowed as described in the SBR but they "drag along" any associated requirements or obligations defined in their own respective standards.

**Comment by srdavidson** [comment]
See 
https://github.com/srdavidson/smime/compare/92e603118197fc4e77216896680bdee7da4e28cc...29b985f602d1bcba42fbb8c1296c609f588671d4

**Comment by srdavidson** [comment]
@XolphinMartijn There is a recommendation from Russ Housley that third-party extensions SHALL not be marked critical.

**Comment by XolphinMartijn** [comment]
@srdavidson  Correct. We did discuss this yesterday during the SMCWG call, and agreed to not take that into the current text. If the specification calls for it, it should be followed.
