### ISSUE TITLE
Clarity on leaf Maximum Validity Period

### ISSUE THREAD

**Issue by srdavidson** [cabforum/smime#247]
The table for maximum validity in 6.3.2 was intended to cover certificates. There is some confusion because of the RFC-3467 heading which also mentions key pairs.

Proposed fix:

1.	 In 6.3.2 change the table column header to say “Certificate Maximum Validity Period”
2.	Add a para after the table that says “Where escrow is supported in accordance with Section 4.12, the CA MAY retain Subscriber Private Keys past the Certificate Maximum Validity Period.”

**Comment by XolphinMartijn** [comment]
Discussed to include this in the logging ballot. Added in the following commit: https://github.com/XolphinMartijn/smime/commit/be3e835b0d4689cccab261095c3080bb258b64cd
