### ISSUE TITLE
Reference specific version of the TLS BRs rather than the most current version

### ISSUE THREAD

**Issue by XolphinMartijn** [cabforum/smime#250]

**Comment by srdavidson** [comment]
We should also review the version references to NetSec included in the document.

**Comment by srdavidson** [comment]
both are in SMC08

We proposed pinning to a specific version of the TLS BR for the time being because the MPIC ballot would require more substantive changes to the S/MIME BR - which would be difficult to coordinate with the complex discussions and balloting surrounding MPIC at TLS.

**Comment by srdavidson** [comment]
See draft at https://github.com/srdavidson/smime/commit/40ac3d417c8c301bcd866c31f43f49bcb0b3e6b6
