### ISSUE TITLE
Consider adding NetSec audit requirement

### ISSUE THREAD

**Issue by clintwilson** [cabforum/smime#251]
Now that CPA Canada has broken out the Audit Criteria which address assessment of compliance with the CA/B Forum's NCSSRs, we should consider requiring this audit (e.g. `WebTrust Principles and Criteria for Certification Authorities – Network Security – Version 1.7 or later`) within Section 8.4 of the SBRs.

**Comment by srdavidson** [comment]
Something like this?

![image](https://github.com/cabforum/smime/assets/13353897/97abdfd5-9f97-4988-8146-325ddce8d2f7)

**Comment by srdavidson** [comment]
For item 2, according to Dave Chin, the separate reporting for WebTrust for NetSec starts April 1, 2025 and the minimum version should be bumped up to NetSec 2.0

**Comment by srdavidson** [comment]
Should also update the "Additional Compliance Date" table as follows

| -- | NS003 | Comply with Network and Certificate System Security Requirements, Version 2.0 |  November 12, 2024 |

**Comment by srdavidson** [comment]
Draft text may be seen at https://github.com/srdavidson/smime/commit/dc92875d78227ce6eca5ced03a93c2ccaa870a1e

**Comment by srdavidson** [comment]
Note that a similar change needs to occur in the TLS BR.

**Comment by clintwilson** [comment]
FWIW, I have an open PR for this in the TBRs here: https://github.com/cabforum/servercert/pull/514/files
