### ISSUE TITLE
organizationIdentifier

### ISSUE THREAD

**Issue by defacto64** [cabforum/smime#30]
I see that (under 7.1.4.2.2 Subject Distinguished Name Fields) the description of the `organizationalIdentifier` field is still empty. 

Is that just an overlook, or is it waiting for proposal/contributions?

**Comment by srdavidson** [comment]
Pending further discussion, this will be based upon Section 9.2.8 and Appendix H of the EVG.

**Comment by defacto64** [comment]
Are you assuming that, in such a case, the certificate should also contain the special CABF extension `cabfOrganizationIdentifier` defined in paragraph 9.8.2 of the EVG?

**Comment by srdavidson** [comment]
The `organizationalIdentifier` content is now addressed in the draft.  The `cabfOrganizationIdentifier` from the EVG is not included in the SBR.

**Comment by defacto64** [comment]
Fine, thank you.
