### ISSUE TITLE
localityName / stateOrProvinceName

### ISSUE THREAD

**Issue by XolphinMartijn** [cabforum/smime#51]
At current the SMIME pre-BR's are somewhat unclear in regards to the localityName and stateOrProvinceName field requirements.

Section 7.1.4.2.2 reads that, if subject:stateOrProvinceName is absent, subject:localityName is required (and vice-versa).
Yet, Section 7.1.4.2.3 reads that the fields are a MUST NOT for mailbox-validated profiles. While it could be argued that section 7.1.4.2.3 takes precedence, that would then break the logic for 7.1.4.2.{4,5,6}, which have both fields as a MAY.

I'd suggest making the language in 7.1.4.2.2 akind to the SSL BRs, stating:
"Required if the subject:organizationName field, subject:givenName field, or subject:surname field are present and the subject:stateOrProvinceName field is absent.

**Comment by srdavidson** [comment]
k. __Certificate Field:__ `subject:localityName` (OID: 2.5.4.7)  
   __Required__ if the `subject:stateOrProvinceName` field is absent.  
   __Optional__ if the `subject:stateOrProvinceName` field is present.  
   __Contents:__ If present, the `subject:localityName` field MUST contain the Subject's locality information as verified under [Section 3.2.3](#323-authentication-of-organization-identity) or [Section 3.2.4](#324-authentication-of-individual-identity). Required if the `subject:organizationName`, or the `subject:givenName` and/or `subject:surname` fields, are present and the `subject:stateOrProvinceName` field is absent. If the `subject:countryName` field specifies the ISO 3166-1 user-assigned code of XX in accordance with [Section 7.1.4.2.2](#71422-subject-distinguished-name-fields) (g), the `localityName` field MAY contain the Subject's locality and/or state or province information.

l. __Certificate Field:__ `subject:stateOrProvinceName` (OID: 2.5.4.8)  
   __Required__ if `subject:localityName` field is absent.  
   __Optional__ if the `subject:localityName` field is present.  
   __Contents:__ If present, the `subject:stateOrProvinceName` field MUST contain the Subject's state or province information as verified under [Section 3.2.3](#323-authentication-of-organization-identity) or [Section 3.2.4](#324-authentication-of-individual-identity). Required if the `subject:organizationName`, or the `subject:givenName` and/or `subject:surname` fields, are present and the `subject:localityName` field is absent.  If the `subject:countryName` field specifies the ISO 3166-1 user-assigned code of XX in accordance with [Section 7.1.4.2.2](#71422-subject-distinguished-name-fields) (g), the `subject:stateOrProvinceName` field MAY contain the full name of the Subject's country information.

**Comment by XolphinMartijn** [comment]
@srdavidson I'd simplify it a bit more, now it first states it's required when stateOrProvinceName is absent yet later on in the Contents section adds the second "required if" trigger. My proposal would be:

k. **Certificate Field**: subject:localityName (OID: 2.5.4.7)
**Required** if the subject:organizationName, or the subject:givenName and/or subject:surname fields, are present and the subject:stateOrProvinceName field is absent
**Optional** if the subject:stateOrProvinceName field is present.
**Contents:** If present, the subject:localityName field MUST contain the Subject's locality information as verified under [Section 3.2.3](https://github.com/cabforum/smime/issues/51#323-authentication-of-organization-identity) or [Section 3.2.4](https://github.com/cabforum/smime/issues/51#324-authentication-of-individual-identity). If the subject:countryName field specifies the ISO 3166-1 user-assigned code of XX in accordance with [Section 7.1.4.2.2](https://github.com/cabforum/smime/issues/51#71422-subject-distinguished-name-fields) (g), the localityName field MAY contain the Subject's locality and/or state or province information.

l. **Certificate Field**: subject:stateOrProvinceName (OID: 2.5.4.8)
**Required** if the subject:organizationName, or the subject:givenName and/or subject:surname fields, are present and the subject:localityName field is absent.
**Optional** if the subject:localityName field is present.
**Contents**: If present, the subject:stateOrProvinceName field MUST contain the Subject's state or province information as verified under [Section 3.2.3](https://github.com/cabforum/smime/issues/51#323-authentication-of-organization-identity) or [Section 3.2.4](https://github.com/cabforum/smime/issues/51#324-authentication-of-individual-identity). If the subject:countryName field specifies the ISO 3166-1 user-assigned code of XX in accordance with [Section 7.1.4.2.2](https://github.com/cabforum/smime/issues/51#71422-subject-distinguished-name-fields) (g), the subject:stateOrProvinceName field MAY contain the full name of the Subject's country information.
