### ISSUE TITLE
subject:JOI fields - Yes or No?

### ISSUE THREAD

**Issue by XolphinMartijn** [cabforum/smime#58]
Do we want to allows the 3 subject:JOI fields in Multipurpose and Strict profiles?

Section 7.1.4.2.3 and .4 do not allow it, yet 3.2.3.1.1 bullet 2 seems to intend that we do want to allow this.

I can get a pull request setup, but before I do, which way do we want to move?
I would be inclined to allow the fields in question on OV and SV certificates

**Comment by srdavidson** [comment]
The intent was not to use the EV JOI fields in certificates, but to rely upon the simpler organizationalIdentifier attribute.
