### ISSUE TITLE
Definitions

### ISSUE THREAD

**Issue by Joanna-TrustCor** [cabforum/smime#65]
I may have missed something, but I cannot find definitions or descriptions of Legacy, Strict and Multipurpose. Can we possibly add these to definitions?

**Comment by srdavidson** [comment]
Thanks for catching this!  I really appreciate your close read.  Willfix, roughly like...

- Legacy Profile: The S/MIME Legacy Profiles provide flexibility for existing reasonable S/MIME certificate practices to become auditable under the S/MIME Baseline Requirements. This includes options for Subject DN attributes, extKeyUsage, and other extensions. The Legacy Profiles will be deprecated in the future.
- Multipurpose Profile: The S/MIME Multipurpose Profiles are aligned with the more defined Strict Profiles, but with additional options for extKeyUsage and other extensions. This is intended to allow flexibility for crossover use cases between document signing and secure email. 
- Strict Profile: The S/MIME Strict Profiles are the long term target for S/MIME Certificates with extKeyUsage limited to emailProtection, and stricter use of Subject DN attributes and other extensions.
