### ISSUE TITLE
CAA

### ISSUE THREAD

**Issue by srdavidson** [cabforum/smime#7]
In order not to delay adoption of the initial certificate profiles, it seems unlikely that v1 of the S/MIME BR will address DNS Certification Authority Authorization (CAA).

A subsequent version of the S/MIME BR can define and register property tags specific to the S/MIME use case.

It is to be decided if v1 should explicitly state that the issue, issuewild, and iodef property tags do not apply to the S/MIME BR.

Also for consideration: the TLS use case envisages checking CAA before every certificate issuance.  This may not be feasible for S/MIME processes which may involve rapid, repeated issuance using the same email domains.

**Comment by RufusJWB** [comment]
I would explicitly state it. We have seen to often in the CA/B forum that old discussions were only remembered by few people because they never made their way into the BRGs.

**Comment by srdavidson** [comment]
> What process do you have in mind for S/MIME that would be so different compared to TLS and make it non-feasible?

My comment is based on the following assumption: for TLS it is relatively rare to have high volume issuance requiring CAA checks on the same domain in tight time proximity.  To the contrary, that would be quite common for S/MIME.

- If CAA were adopted for S/MIME, would a bulk issuance of 1000 S/MIME certs on the same domain require 1000 corresponding CAA verifications?

- The BR states "If the CA issues, they MUST do so within the TTL of the CAA record, or 8 hours, whichever is greater."  If I recall correctly, this text was provided to accommodate a delay between the CA conducting the CAA check for a cert and the CA issuing a cert.  However, could it be interpreted to allow the CA to issue multiple corresponding certs within "the TTL of the CAA record, or 8 hours, whichever is greater"?

**Comment by dzacharo** [comment]
Stephen,

>     * could it be interpreted to allow the CA to issue multiple corresponding certs within "the TTL of the CAA record, or 8 hours, whichever is greater"?

I would encourage you to bring this question to the servercert WG mailing list.

**Comment by chrisbn** [comment]
Could we re-phrase the CAA section 3.2.2.4 to use RFC 2119 wording, to make it a bit more explicit that CAA SHALL NOT be used for SMIME?

For example: "The CA SHALL NOT perform a check for CAA records."

**Comment by CBonnell** [comment]
> Could we re-phrase the CAA section 3.2.2.4 to use RFC 2119 wording, to make it a bit more explicit that CAA SHALL NOT be used for SMIME?
> 
> For example: "The CA SHALL NOT perform a check for CAA records."

This would mean that it is mis-issuance if the CA performs a CAA check prior to issuance. To me, that seems overly restrictive for a policy to do, as CAs may generally be more restrictive than the standard dictates as part of their validation/pre-issuance processes.

**Comment by RufusJWB** [comment]
> To me, that seems overly restrictive for a policy to mandate, as CAs may generally be more restrictive than the standard dictates as part of their validation/pre-issuance processes.

I share your opinion. Actually I would even encourage CAs to experiment with CAA records in the context of S/MIME certificates as they have brought clear benefits to the TLS certificate eco system.

**Comment by chrisbn** [comment]
Valid points. So would the solution be to make it optional "The CA MAY perform a check for CAA records"?

**Comment by CBonnell** [comment]
The specification for the "issuemail" Property Tag is now an RFC: https://www.rfc-editor.org/rfc/rfc9495.html.
