### ISSUE TITLE
non-ASCII-characters (was: Diacritic characters)

### ISSUE THREAD

**Issue by RufusJWB** [cabforum/smime#80]
In https://github.com/cabforum/smime/blob/d2168d270b81a19f434f1a65c5bd4dad7eebfcc9/SBR.md?plain=1#L531 we require
>where names use diacritics or other characters that are not supported by Relying Party applications, the CA SHOULD

How is the CA supposed to know, which characters 'are not support by Relying Party applications'? I would propose to remove this sentence as it adds no value.

Also, I would remove the following examples, as they are heavily euro centric.

**Comment by vanbroup** [comment]
Maybe it should just make a reference to the Unicode® Standard Annex 15 (Unicode normalization forms) and allow the removal of characters in the Nonspacing Mark (Mn) category.

https://www.unicode.org/reports/tr15/
https://www.compart.com/en/unicode/category/Mn

With some simple magic all accents can be removed from every string:

https://go.dev/blog/normalization (Performing magic)

I would also like to question if the representation of these accents is an actual issue? Do we have examples of where this is causing issues?

**Comment by RufusJWB** [comment]
> Maybe it should just make a reference to the Unicode® Standard Annex 15 (Unicode normalization forms) and allow the removal of characters in the Nonspacing Mark (Mn) category.

I'm not sure, if this covers, what the SBRs want to achieve. With normalization one would transform

> nörmalization --> No\u0308rmalization

But we want to transform `nörmalization` into `noermalization`

**Comment by RufusJWB** [comment]
Reading Wikipedia about Diacritic characters and their substitution rules in different languages, I start to wonder if defining anything more than `CAs MAY substitute diacritic characters` is a full blown Ph.D. thesis. ..

**Comment by vanbroup** [comment]
Simple Unicode normalization is not sufficient, but check the filter magic using the Unicode Nonspacing Mark (Mn) category. 

This example does exactly what the BR describes:

https://go.dev/play/p/rpQP1ls4LB8

**Comment by RufusJWB** [comment]
> Simple Unicode normalization is not sufficient, but check the filter magic using the Unicode Nonspacing Mark (Mn) category.
> 
> This example does exactly what the BR describes:
> 
> https://go.dev/play/p/rpQP1ls4LB8

But it is not doing what is, IMHO, intended by the SBR. Take this example: https://go.dev/play/p/WU7KeJdPHxx. It transforms the second most popular family name in Germany `Müller` into `Muller`. This might be correct for the purpose of 'compatibility equivalence' but it is clearly not correct by the rules of the German language. It should become `Mueller`.

**Comment by vanbroup** [comment]
Not sure if there is anything to detect or translate that but it's it not that both are officially accepted anyway?

So would it be needed to specify this as a rule? And can you take all local language rules into consideration for the BR?

**Comment by RufusJWB** [comment]
And it doesn't help at all for non-latin characters: https://go.dev/play/p/hargtM-qwEB. `Александр Солженицын` stays `Александр Солженицын`.

**Comment by RufusJWB** [comment]
> Not sure if there is anything to detect or translate that but it's it not that both are officially accepted anyway?
> 
> So would it be needed to specify this as a rule? And can you take all local language rules into consideration for the BR?

I'll propose a wording in a PR.

**Comment by vanbroup** [comment]
> And it doesn't help at all for non-latin characters: https://go.dev/play/p/hargtM-qwEB. `Александр Солженицын` stays `Александр Солженицын`.

This is not about diacritics, I don't think this value can be represented in ASCII without being translated.

**Comment by CBonnell** [comment]
> How is the CA supposed to know, which characters 'are not support by Relying Party applications'? I would propose to remove this sentence as it adds no value.

The intent of the current language is that if the CA is made aware of a Relying Party application that cannot support non-ASCII characters, then it MAY convert subject attribute values to ASCII provided that the CA documents its conversion process in its CP/CPS. The CA's Subscribers or Relying Parties can inform them of the need to use exclusively ASCII characters.

I think any further specificity in this area (mandating specific normalization algorithms, etc.) will be incredibly complex and very locale-specific.

**Comment by RufusJWB** [comment]
> > And it doesn't help at all for non-latin characters: https://go.dev/play/p/hargtM-qwEB. `Александр Солженицын` stays `Александр Солженицын`.
> 
> This is not about diacritics, I don't think this value can be represented in ASCII without being translated.

This is true. We have a general problem with non-ASCII-characters and diacritic characters are only a sub-set of those non-ASCII-characters.

**Comment by srdavidson** [comment]
Changed text has been proposed for section 3.1.4.
