### ISSUE TITLE
CP/CPS updates at least every 365 days

### ISSUE THREAD

**Issue by BenWilson-Mozilla** [cabforum/smime#92]
Section 2 should be amended to delete "annually update" and add a following sentence that says, "The CA SHALL review and update its CP and/or CPS at least every 365 days, and indicate the new version by incrementing the version number and adding a dated changelog entry, even if no other changes are made."  Or something similar.  Rationale:  Some CAs have argued that "annually update" means calendar year, which leads to a period of as much as 730 days between CP/CPS updates.

**Comment by srdavidson** [comment]
Thanks Ben - have updated as follows
# 2. PUBLICATION AND REPOSITORY RESPONSIBILITIES
The CA SHALL develop, implement, and enforce a Certificate Policy and/or Certification Practice Statement (CP and/or CPS) that describes in detail how the CA implements the latest version of these Requirements. The CA SHALL review and update its CP and/or CPS at least every 365 days, incrementing the version number and adding a dated changelog entry even if no other changes are made.
